import * as pg from 'pg';
import type { IncomingHttpHeaders } from 'node:http';
import type { HTTPClientOptions } from './types';
export default class HttpClient {
    private _opt;
    private _client;
    private _store;
    private _pub_sufix;
    private _agent;
    private _headers;
    constructor(opt?: HTTPClientOptions);
    bootup(client?: pg.Client): Promise<void>;
    teardown(): Promise<void>;
    private timeout;
    private connectPg;
    private createTables;
    private loadPublicSufixes;
    private loadCookieStore;
    private validateCookieDate;
    private computeDefaultPath;
    private computeCanonHostname;
    private domainMatch;
    private pathMatch;
    private parseSetCookie;
    private computeTempStore;
    private updateStore;
    private parseCookie;
    private handleHTTPError;
    private printDebug;
    request(host: string, path: string, cb: (data: Buffer, headers?: IncomingHttpHeaders) => void, options?: ScraperRequestOptions): Promise<number>;
}
